# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2_ip_op.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
import time

ardconnect = serial.Serial('com4',9600)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 60, 361, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 311, 111))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 280, 361, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(50, 50, 95, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 50, 95, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 110, 95, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(230, 110, 95, 31))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(95, 14, 217)")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
#--------------------------------------------------------------------------------
        # variable declaration
        self.pushButton.clicked.connect(self.pressedbutton)

#---------------------------------------------------------------------------------
        # method declaration
    def pressedbutton(self):
        if self.radioButton.isChecked():
            # self.label.setText('option 1 pressed')
            ardconnect.write(b'1')
            var = ardconnect.readline().decode('utf-8')
            self.label.setText(str(var))
            print(var)
            time.sleep(0.1)
            
        elif self.radioButton_2.isChecked():
             ardconnect.write(b'2')
             var = ardconnect.readline().decode('utf-8')
             self.label.setText(str(var))
             print(var)
             time.sleep(0.1)
             
        elif self.radioButton_3.isChecked():
             ardconnect.write(b'3')
             var = ardconnect.readline().decode('utf-8')
             self.label.setText(str(var))
             print(var)
             time.sleep(0.1)
             
        elif self.radioButton_4.isChecked():
             ardconnect.write(b'4')
             var = ardconnect.readline().decode('utf-8')
             self.label.setText(str(var))
             print(var)
             time.sleep(0.1)
#---------------------------------------------------------------------------------


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "arduino ip/op"))
        self.groupBox.setTitle(_translate("MainWindow", "output box"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "input box"))
        self.pushButton.setText(_translate("MainWindow", "send command"))
        self.radioButton.setText(_translate("MainWindow", "option1"))
        self.radioButton_2.setText(_translate("MainWindow", "option2"))
        self.radioButton_3.setText(_translate("MainWindow", "option3"))
        self.radioButton_4.setText(_translate("MainWindow", "option4"))
        self.label_2.setText(_translate("MainWindow", "Interfacing with arduino from a custom GUI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
