# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import time
import serial

ard = serial.Serial('com4',9600)

class Worker(QRunnable):
    def __init__(self, fn, *args, **kwargs):
        super(Worker,self).__init__()
        self.fn = fn
        self.args = args
        self.kwargs = kwargs
        
    @pyqtSlot()
    def run(self):
        '''
        Your code goes in this function
        '''
        self.fn(*self.args, **self.kwargs)

class Ui_MainWindow(object):
    
    def __init__(self, *args, **kwargs):
        super(Ui_MainWindow, self).__init__(*args, **kwargs)
        self.threadpool = QThreadPool()
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 857)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.G_HH = QtWidgets.QGroupBox(self.centralwidget)
        self.G_HH.setGeometry(QtCore.QRect(240, 50, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_HH.setFont(font)
        self.G_HH.setObjectName("G_HH")
        self.L_hh_values = QtWidgets.QLabel(self.G_HH)
        self.L_hh_values.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.L_hh_values.setAlignment(QtCore.Qt.AlignCenter)
        self.L_hh_values.setObjectName("L_hh_values")
        self.G_HU = QtWidgets.QGroupBox(self.centralwidget)
        self.G_HU.setGeometry(QtCore.QRect(600, 50, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_HU.setFont(font)
        self.G_HU.setObjectName("G_HU")
        self.L_hu_values = QtWidgets.QLabel(self.G_HU)
        self.L_hu_values.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.L_hu_values.setAlignment(QtCore.Qt.AlignCenter)
        self.L_hu_values.setObjectName("L_hu_values")
        self.G_HU2 = QtWidgets.QGroupBox(self.centralwidget)
        self.G_HU2.setGeometry(QtCore.QRect(600, 260, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_HU2.setFont(font)
        self.G_HU2.setObjectName("G_HU2")
        self.L_hu_values2 = QtWidgets.QLabel(self.G_HU2)
        self.L_hu_values2.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.L_hu_values2.setAlignment(QtCore.Qt.AlignCenter)
        self.L_hu_values2.setObjectName("L_hu_values2")
        self.G_HA = QtWidgets.QGroupBox(self.centralwidget)
        self.G_HA.setGeometry(QtCore.QRect(240, 260, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_HA.setFont(font)
        self.G_HA.setObjectName("G_HA")
        self.L_ha_values = QtWidgets.QLabel(self.G_HA)
        self.L_ha_values.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.L_ha_values.setAlignment(QtCore.Qt.AlignCenter)
        self.L_ha_values.setObjectName("L_ha_values")
        self.L_meter1R = QtWidgets.QLabel(self.centralwidget)
        self.L_meter1R.setGeometry(QtCore.QRect(240, 200, 111, 41))
        self.L_meter1R.setStyleSheet("background-color:white;")
        self.L_meter1R.setText("")
        self.L_meter1R.setObjectName("L_meter1R")
        self.L_meter2R = QtWidgets.QLabel(self.centralwidget)
        self.L_meter2R.setGeometry(QtCore.QRect(410, 200, 111, 41))
        self.L_meter2R.setStyleSheet("background-color:white;")
        self.L_meter2R.setText("")
        self.L_meter2R.setObjectName("L_meter2R")
        self.L_meter3R = QtWidgets.QLabel(self.centralwidget)
        self.L_meter3R.setGeometry(QtCore.QRect(580, 200, 111, 41))
        self.L_meter3R.setStyleSheet("background-color:white;")
        self.L_meter3R.setText("")
        self.L_meter3R.setObjectName("L_meter3R")
        self.L_meter4R = QtWidgets.QLabel(self.centralwidget)
        self.L_meter4R.setGeometry(QtCore.QRect(750, 200, 111, 41))
        self.L_meter4R.setStyleSheet("background-color:white;")
        self.L_meter4R.setText("")
        self.L_meter4R.setObjectName("L_meter4R")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 160, 139, 24))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(190, -10, 20, 841))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.G_comm = QtWidgets.QGroupBox(self.centralwidget)
        self.G_comm.setGeometry(QtCore.QRect(20, 480, 161, 171))
        self.G_comm.setObjectName("G_comm")
        self.L_commCheck = QtWidgets.QLabel(self.G_comm)
        self.L_commCheck.setGeometry(QtCore.QRect(14, 55, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.L_commCheck.setFont(font)
        self.L_commCheck.setAlignment(QtCore.Qt.AlignCenter)
        self.L_commCheck.setObjectName("L_commCheck")
        self.G_meters = QtWidgets.QGroupBox(self.centralwidget)
        self.G_meters.setGeometry(QtCore.QRect(20, 39, 161, 281))
        self.G_meters.setObjectName("G_meters")
        self.R_meter1 = QtWidgets.QRadioButton(self.G_meters)
        self.R_meter1.setGeometry(QtCore.QRect(20, 50, 121, 20))
        self.R_meter1.setObjectName("R_meter1")
        self.R_meter2 = QtWidgets.QRadioButton(self.G_meters)
        self.R_meter2.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.R_meter2.setObjectName("R_meter2")
        self.R_meter3 = QtWidgets.QRadioButton(self.G_meters)
        self.R_meter3.setGeometry(QtCore.QRect(20, 170, 121, 20))
        self.R_meter3.setObjectName("R_meter3")
        self.R_meter4 = QtWidgets.QRadioButton(self.G_meters)
        self.R_meter4.setGeometry(QtCore.QRect(20, 230, 121, 20))
        self.R_meter4.setObjectName("R_meter4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
#--------------------------------------------------------------------------
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setText('push me')
        
        # self.timer = QTimer()
        # self.timer.setInterval(1000)
        # self.timer.timeout.connect(self.test)
        # self.timer.start()
        
        self.button.setGeometry(QtCore.QRect(500, 600, 211, 41))
        self.count = 0
        self.button.clicked.connect(self.oh_no)
        
        
#--------------------------------------------------------------------------
    def test(self):
        self.L_hu_values2.setText(str(self.count))
        self.count += 1
    
    def execute_this_fn(self):
        
        while True:
            ard.write(b'1')
            var = [0,0,0,0]
            var[0] = ard.readline().decode('utf-8')
            var[1] = ard.readline().decode('utf-8')
            var[2] = ard.readline().decode('utf-8')
            var[3] = ard.readline().decode('utf-8')
            self.L_meter1R.setText(str(var[0]))
            self.L_meter2R.setText(str(var[1]))
            self.L_meter3R.setText(str(var[2]))
            self.L_meter4R.setText(str(var[3]))
            #print(var[0])
            time.sleep(1)
            
            # ard.write(b'2')
            # var = ard.readline().decode('utf-8')
            # self.L_meter2R.setText(str(var))
            # time.sleep(1)
            
    def oh_no(self):
        worker = Worker(self.execute_this_fn)
        self.threadpool.start(worker)

        
#--------------------------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "arduino GUI"))
        self.G_HH.setTitle(_translate("MainWindow", "HH"))
        self.L_hh_values.setText(_translate("MainWindow", "HH values"))
        self.G_HU.setTitle(_translate("MainWindow", "HU"))
        self.L_hu_values.setText(_translate("MainWindow", "HU values"))
        self.G_HU2.setTitle(_translate("MainWindow", "HU"))
        self.L_hu_values2.setText(_translate("MainWindow", "HU values"))
        self.G_HA.setTitle(_translate("MainWindow", "HA"))
        self.L_ha_values.setText(_translate("MainWindow", "HA values"))
        self.label_9.setText(_translate("MainWindow", "meter reading :"))
        self.G_comm.setTitle(_translate("MainWindow", "communication"))
        self.L_commCheck.setText(_translate("MainWindow", "OK"))
        self.G_meters.setTitle(_translate("MainWindow", "meter:"))
        self.R_meter1.setText(_translate("MainWindow", "meter 1"))
        self.R_meter2.setText(_translate("MainWindow", "meter 2"))
        self.R_meter3.setText(_translate("MainWindow", "meter 3"))
        self.R_meter4.setText(_translate("MainWindow", "meter 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
