# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiForGPIB.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyvisa

rm = pyvisa.ResourceManager()
a = rm.list_resources()
b = str(a)[1:][:-1]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.G_selectmeter = QtWidgets.QGroupBox(self.centralwidget)
        self.G_selectmeter.setGeometry(QtCore.QRect(20, 10, 741, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_selectmeter.setFont(font)
        self.G_selectmeter.setObjectName("G_selectmeter")
        self.B_initialize = QtWidgets.QPushButton(self.G_selectmeter)
        self.B_initialize.setGeometry(QtCore.QRect(530, 120, 141, 51))
        self.B_initialize.setObjectName("B_initialize")
        self.R_multimeter1 = QtWidgets.QRadioButton(self.G_selectmeter)
        self.R_multimeter1.setGeometry(QtCore.QRect(80, 60, 181, 41))
        self.R_multimeter1.setObjectName("R_multimeter1")
        self.R_multimeter2 = QtWidgets.QRadioButton(self.G_selectmeter)
        self.R_multimeter2.setGeometry(QtCore.QRect(80, 140, 151, 41))
        self.R_multimeter2.setObjectName("R_multimeter2")
        self.G_ipToMeter = QtWidgets.QGroupBox(self.centralwidget)
        self.G_ipToMeter.setGeometry(QtCore.QRect(20, 290, 741, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_ipToMeter.setFont(font)
        self.G_ipToMeter.setObjectName("G_ipToMeter")
        self.E_currentEenter = QtWidgets.QLineEdit(self.G_ipToMeter)
        self.E_currentEenter.setGeometry(QtCore.QRect(130, 70, 113, 31))
        self.E_currentEenter.setObjectName("E_currentEenter")
        self.E_voltageEenter = QtWidgets.QLineEdit(self.G_ipToMeter)
        self.E_voltageEenter.setGeometry(QtCore.QRect(420, 70, 113, 31))
        self.E_voltageEenter.setObjectName("E_voltageEenter")
        self.label_current = QtWidgets.QLabel(self.G_ipToMeter)
        self.label_current.setGeometry(QtCore.QRect(130, 40, 111, 31))
        self.label_current.setObjectName("label_current")
        self.label_voltage = QtWidgets.QLabel(self.G_ipToMeter)
        self.label_voltage.setGeometry(QtCore.QRect(420, 40, 111, 31))
        self.label_voltage.setObjectName("label_voltage")
        self.label_mA = QtWidgets.QLabel(self.G_ipToMeter)
        self.label_mA.setGeometry(QtCore.QRect(240, 70, 55, 21))
        self.label_mA.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_mA.setObjectName("label_mA")
        self.label_V = QtWidgets.QLabel(self.G_ipToMeter)
        self.label_V.setGeometry(QtCore.QRect(530, 70, 55, 21))
        self.label_V.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_V.setObjectName("label_V")
        self.label_output = QtWidgets.QLabel(self.G_ipToMeter)
        self.label_output.setGeometry(QtCore.QRect(90, 180, 81, 41))
        self.label_output.setObjectName("label_output")
        self.L_outputPrint = QtWidgets.QLabel(self.G_ipToMeter)
        self.L_outputPrint.setGeometry(QtCore.QRect(170, 180, 291, 41))
        self.L_outputPrint.setStyleSheet("background-color:white")
        self.L_outputPrint.setText("")
        self.L_outputPrint.setObjectName("L_outputPrint")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #---------------------------------------------------------------------------
        self.B_initialize.clicked.connect(self.checkTest)
        
    #---------------------------------------------------------------------------
    def inputed(self):
        self.L_outputPrint.setText(b)
    
    def checkTest(self):
        if self.R_multimeter1.isChecked():
            # print('worked')
            meter1current = self.E_currentEenter.text()
            meter1voltage = self.E_voltageEenter.text()
            print('current:',meter1current,' voltage:',meter1voltage)
        elif self.R_multimeter2.isChecked():
             meter2current = self.E_currentEenter.text()
             meter2voltage = self.E_voltageEenter.text()
             print('current:',meter2current,' voltage:',meter2voltage)

    #---------------------------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "testphaseGUI  GPIB"))
        self.G_selectmeter.setTitle(_translate("MainWindow", "select the multimeter"))
        self.B_initialize.setText(_translate("MainWindow", "Initialize"))
        self.R_multimeter1.setText(_translate("MainWindow", "multimeter 1"))
        self.R_multimeter2.setText(_translate("MainWindow", "multimeter 2"))
        self.G_ipToMeter.setTitle(_translate("MainWindow", "input to meters "))
        self.label_current.setText(_translate("MainWindow", "current"))
        self.label_voltage.setText(_translate("MainWindow", "voltage"))
        self.label_mA.setText(_translate("MainWindow", "mA"))
        self.label_V.setText(_translate("MainWindow", "V"))
        self.label_output.setText(_translate("MainWindow", "output :"))

print('last')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
